# Generated by Django 5.2.6 on 2025-10-23 06:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import stamping.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreakTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_istirahat', models.CharField(default='istirahat', max_length=100)),
                ('waktu_mulai', models.TimeField()),
                ('waktu_selesai', models.TimeField()),
                ('shift', models.IntegerField(default=1)),
                ('hari', models.IntegerField(blank=True, choices=[(0, 'Senin'), (1, 'Selasa'), (2, 'Rabu'), (3, 'Kamis'), (4, 'Jumat'), (5, 'Sabtu')], help_text='Kosongkan jika istirahat ini berlaku setiap hari (kecuali Minggu)', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='detailjob',
            fields=[
                ('id_detailjob', models.AutoField(primary_key=True, serialize=False)),
                ('plan_qty', models.PositiveIntegerField()),
                ('plan_ct', models.DecimalField(decimal_places=2, max_digits=6)),
                ('actual_qty', models.PositiveIntegerField(default=0, help_text='Jumlah kuantitas aktual yang sudah selesai dikerjakan.')),
                ('urutan', models.PositiveIntegerField(default=0, help_text='Urutan job dalam satu hari (0, 1, 2, ...)')),
                ('repair_staging', models.PositiveIntegerField(default=0, verbose_name='Repair (Staging)')),
                ('reject_staging', models.PositiveIntegerField(default=0, verbose_name='Reject (Staging)')),
            ],
        ),
        migrations.CreateModel(
            name='itemproduksi',
            fields=[
                ('id_itemproduksi', models.AutoField(primary_key=True, serialize=False)),
                ('job_number', models.CharField(max_length=50)),
                ('part_number', models.CharField(max_length=50)),
                ('customer', models.CharField(max_length=100)),
                ('cycle_time', models.FloatField(default=0.0)),
            ],
        ),
        migrations.CreateModel(
            name='job',
            fields=[
                ('id_job', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('plan_repair_percentage', models.FloatField(blank=True, default=0.0, null=True)),
                ('plan_reject_percentage', models.FloatField(blank=True, default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='karyawan',
            fields=[
                ('id_karyawan', models.AutoField(primary_key=True, serialize=False)),
                ('nama_karyawan', models.CharField(max_length=100)),
                ('nrp_karyawan', models.CharField(max_length=20, unique=True)),
                ('jabatan', models.CharField(choices=[('admin', 'admin'), ('operator', 'operator'), ('leader', 'leader'), ('foreman', 'foreman'), ('supervisor', 'supervisor')], max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='dandori',
            fields=[
                ('id_dandori', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_dandori', models.CharField(choices=[('waktu_dandori', 'Waktu Dandori'), ('material_change', 'Material Change Time'), ('variant_change', 'Variant Change Time')], max_length=30)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dandoris', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='ActualItem',
            fields=[
                ('id_actual_item', models.AutoField(primary_key=True, serialize=False)),
                ('waktu_selesai', models.DateTimeField(auto_now_add=True)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actual_items', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='downtime',
            fields=[
                ('id_downtime', models.AutoField(primary_key=True, serialize=False)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downtimes', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='detail_dt',
            fields=[
                ('id_detaildt', models.AutoField(primary_key=True, serialize=False)),
                ('jenisdowntime', models.CharField(choices=[('prod_t', 'prod_t'), ('mat_t', 'mat_t'), ('dies_t', 'dies_t'), ('mach_t', 'mach_t'), ('log_t', 'log_t')], max_length=10)),
                ('problem_dt', models.TextField(blank=True, null=True)),
                ('penyebab_dt', models.TextField(blank=True, null=True)),
                ('action_dt', models.TextField(blank=True, null=True)),
                ('start_downtime', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_downtime', models.DateTimeField(blank=True, null=True)),
                ('pic_downtime', models.CharField(blank=True, max_length=100, null=True)),
                ('id_downtime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamping.downtime')),
            ],
        ),
        migrations.CreateModel(
            name='handwork',
            fields=[
                ('id_handwork', models.AutoField(primary_key=True, serialize=False)),
                ('qty_repair', models.PositiveIntegerField(default=0)),
                ('ct1_start', models.DateTimeField(blank=True, null=True)),
                ('ct1_finish', models.DateTimeField(blank=True, null=True)),
                ('ct2_start', models.DateTimeField(blank=True, null=True)),
                ('ct2_finish', models.DateTimeField(blank=True, null=True)),
                ('ct3_start', models.DateTimeField(blank=True, null=True)),
                ('ct3_finish', models.DateTimeField(blank=True, null=True)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handworks', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='detailhandwork',
            fields=[
                ('id_detailhw', models.AutoField(primary_key=True, serialize=False)),
                ('problem_hw', models.TextField(blank=True, null=True)),
                ('is_ok', models.BooleanField(default=False)),
                ('foto_sebelum', models.ImageField(blank=True, null=True, upload_to='handwork_photos/')),
                ('foto_sesudah', models.ImageField(blank=True, null=True, upload_to='handwork_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('id_handwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_items', to='stamping.handwork')),
            ],
        ),
        migrations.CreateModel(
            name='idletime',
            fields=[
                ('id_idle', models.AutoField(primary_key=True, serialize=False)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idle_times', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='detail_idle',
            fields=[
                ('id_detaild', models.AutoField(primary_key=True, serialize=False)),
                ('start_idle', models.DateTimeField(default=django.utils.timezone.now)),
                ('finish_idle', models.DateTimeField(blank=True, null=True)),
                ('reason_idle', models.TextField(blank=True, null=True)),
                ('id_idle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamping.idletime')),
            ],
        ),
        migrations.AddField(
            model_name='detailjob',
            name='id_itemproduksi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamping.itemproduksi'),
        ),
        migrations.AddField(
            model_name='detailjob',
            name='id_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detail_jobs', to='stamping.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='id_karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamping.karyawan'),
        ),
        migrations.AddField(
            model_name='detailjob',
            name='machine_used',
            field=models.ManyToManyField(related_name='detail_jobs', to='stamping.machine'),
        ),
        migrations.CreateModel(
            name='problem',
            fields=[
                ('id_problem', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_masalah', models.CharField(max_length=100)),
                ('action_prob', models.TextField(blank=True, null=True)),
                ('notes_prob', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='fotoproblem',
            fields=[
                ('id_fotoprob', models.AutoField(primary_key=True, serialize=False)),
                ('foto_problem', models.ImageField(blank=True, null=True, upload_to=stamping.models.PathForFotoProblem())),
                ('id_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stamping.problem')),
            ],
        ),
        migrations.CreateModel(
            name='productionline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaline', models.CharField(max_length=50)),
                ('shift', models.IntegerField()),
                ('kapasitasline', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('namaline', 'shift'), name='unique_line_shift_combination')],
            },
        ),
        migrations.AddField(
            model_name='job',
            name='id_productionline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stamping.productionline'),
        ),
        migrations.AddField(
            model_name='itemproduksi',
            name='production_lines',
            field=models.ManyToManyField(blank=True, related_name='items_produksi', to='stamping.productionline'),
        ),
        migrations.CreateModel(
            name='productionplan',
            fields=[
                ('id_production_plan', models.AutoField(primary_key=True, serialize=False)),
                ('gsph_plan', models.PositiveIntegerField()),
                ('stroke_plan', models.PositiveIntegerField()),
                ('repair_plan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('reject_plan', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('idle_plan', models.PositiveIntegerField()),
                ('mp', models.PositiveIntegerField()),
                ('ot_plan', models.PositiveIntegerField()),
                ('gsph_actual', models.PositiveIntegerField(default=0)),
                ('stroke_actual', models.PositiveIntegerField(default=0)),
                ('ot_actual', models.PositiveIntegerField(default=0)),
                ('id_job', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productionplan', to='stamping.job')),
            ],
        ),
        migrations.CreateModel(
            name='qcheck',
            fields=[
                ('id_qcheck', models.AutoField(primary_key=True, serialize=False)),
                ('jenis_qcheck', models.CharField(choices=[('initial_qcheck', 'Initial Q Check'), ('material_change_check', 'Material Change Check'), ('variant_change_check', 'Variant Change Check (SME)')], max_length=30)),
                ('hasil_qcheck', models.CharField(max_length=100)),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('finish_time', models.DateTimeField(blank=True, null=True)),
                ('id_detailjob', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qchecks', to='stamping.detailjob')),
            ],
        ),
        migrations.CreateModel(
            name='rootcause',
            fields=[
                ('id_rc', models.AutoField(primary_key=True, serialize=False)),
                ('deskripsi_rc', models.CharField(max_length=500)),
                ('id_problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='root_causes', to='stamping.problem')),
            ],
        ),
        migrations.CreateModel(
            name='fotorc',
            fields=[
                ('id_fotorc', models.AutoField(primary_key=True, serialize=False)),
                ('fotorc', models.ImageField(blank=True, null=True, upload_to=stamping.models.PathForFotoRC())),
                ('id_rc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='stamping.rootcause')),
            ],
        ),
    ]
